### ISSUE TITLE
Link to live app

### ISSUE THREAD

**Issue by GitauHarrison** [michaelzdrav/taskmate#8]
Hey, curious if there is a live link to this. I'd be interested to check it out.

**Comment by michaelzdrav** [comment]
Hi, I will bring up a live link to this within 24 hours. Feel free to execute the make commands in the description if you want to run it locally now.

**Comment by michaelzdrav** [comment]
Hi @GitauHarrison here it is: [taskmate](http://taskmate.duckdns.org)

**Comment by GitauHarrison** [comment]
This is a good app. I love the DUE and OVERDUE check (simple but really the central defining feature of the app).

Also, I'm learning a thing or two regarding how you have set up your app. Slightly different from how I do project structures.

I have noticed that one of the things you intend to do is to use Flask SQLAlchemy to allow for room to switch between engines. I was worried that the app had limited you to SQLite as it stands now.

Let me know if you are open to receiving contributions.

**Comment by GitauHarrison** [comment]
Thank you for the invitation.

You are right, the design of the database from the start is a big thing (you'd want to configure it as generically as possible), and that was a big thing for me when I looked through the app.

The choice of TailwindCSS is welcome. 

I am glad to help contribute to the project. Invitation accepted.

You can check if [this time](https://www.gitauharrison.com/help) works well for you. We can adjust it for a first meeting, when you are available, so we can plan on collaboration.
